export const restaurantList = [
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "84229",
			name: "Punjabi Dhaba",
			uuid: "317a42f9-5111-400c-a254-1e2a8b677d64",
			city: "22",
			area: "Paltan Bazaar",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "yyrjmyajqhyjq6mp1gha",
			cuisines: ["North Indian"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 35,
			minDeliveryTime: 35,
			maxDeliveryTime: 35,
			slaString: "35 MINS",
			lastMileTravel: 5.599999904632568,
			slugs: {
				restaurant: "punjabi-dhaba-prince-chowk-race-course-dehradun",
				city: "dehradun",
			},
			cityState: "22",
			address: "59, Gandhi Road, Prince Chowk, Dehradun",
			locality: "Gandhi Road",
			parentId: 1476,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "60% off",
				shortDescriptionList: [
					{
						meta: "60% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹120 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "60% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹120 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=5807654~p=1~eid=00000186-622c-9828-0906-91df0039016e",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "5.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "84229",
				deliveryTime: 35,
				minDeliveryTime: 35,
				maxDeliveryTime: 35,
				lastMileTravel: 5.599999904632568,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "3.6",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "148051",
			name: "Hotel Sunder Palace",
			uuid: "aa4876a4-23dc-4db2-a9b6-9554157a6bae",
			city: "22",
			area: "Majra",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "adwbxvdijp7h7ct0spsk",
			cuisines: ["North Indian", "Chinese"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 32,
			minDeliveryTime: 32,
			maxDeliveryTime: 32,
			slaString: "32 MINS",
			lastMileTravel: 1.7000000476837158,
			slugs: {
				restaurant: "hotel-sunder-palace-majra-patel-nagar",
				city: "dehradun",
			},
			cityState: "22",
			address:
				"Hotel Sunder Palace, Near Punjab and Sind Bank, Majra, Dehradun",
			locality: "Sewla Kalan",
			parentId: 15322,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.7 kms",
			hasSurge: false,
			sla: {
				restaurantId: "148051",
				deliveryTime: 32,
				minDeliveryTime: 32,
				maxDeliveryTime: 32,
				lastMileTravel: 1.7000000476837158,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.8",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "640589",
			name: "Hunger Killer",
			uuid: "24c1a2f4-720f-4615-85a7-8743f85ec731",
			city: "22",
			area: "Majra",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "wx8ewggqmzayjmxejqxe",
			cuisines: ["North Indian", "Fast Food"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 37,
			minDeliveryTime: 37,
			maxDeliveryTime: 37,
			slaString: "37 MINS",
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: "hunger-killer-deh_patel-nagar-deh_patel-nagar",
				city: "dehradun",
			},
			cityState: "22",
			address:
				"HIMADRI ENCLAVE KHASRA NO 9 MAUJA  PITHUWALA PARGANA PACHWA DOON, Pitthuwala, Dehradun Rural, Dehradun, Uttarakhand",
			locality: "Pithuwala Kalan",
			parentId: 104260,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.6 kms",
			hasSurge: false,
			sla: {
				restaurantId: "640589",
				deliveryTime: 37,
				minDeliveryTime: 37,
				maxDeliveryTime: 37,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "640589",
			name: "Hunger Killer",
			uuid: "24c1a2f4-720f-4615-85a7-8743f85ec731",
			city: "22",
			area: "Majra",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "wx8ewggqmzayjmxejqxe",
			cuisines: ["North Indian", "Fast Food"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 37,
			minDeliveryTime: 37,
			maxDeliveryTime: 37,
			slaString: "37 MINS",
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: "hunger-killer-deh_patel-nagar-deh_patel-nagar",
				city: "dehradun",
			},
			cityState: "22",
			address:
				"HIMADRI ENCLAVE KHASRA NO 9 MAUJA  PITHUWALA PARGANA PACHWA DOON, Pitthuwala, Dehradun Rural, Dehradun, Uttarakhand",
			locality: "Pithuwala Kalan",
			parentId: 104260,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.6 kms",
			hasSurge: false,
			sla: {
				restaurantId: "640589",
				deliveryTime: 37,
				minDeliveryTime: 37,
				maxDeliveryTime: 37,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "677107",
			name: "Indori Zayka",
			uuid: "05b5057a-6a49-4827-b55e-569c93c9b82a",
			city: "22",
			area: "Deh_Patel Nagar",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "f34657e4f398eec0e714971b58f8be69",
			cuisines: ["North Indian", "Salads", "Snacks", "Beverages"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 35,
			minDeliveryTime: 35,
			maxDeliveryTime: 35,
			slaString: "35 MINS",
			lastMileTravel: 3,
			slugs: {
				restaurant: "indori-zayka-deh_patel-nagar-deh_patel-nagar",
				city: "dehradun",
			},
			cityState: "22",
			address:
				"7XHX+886, Subhash Nagar, Bharu Wala Grant, Uttarakhand 248002, India",
			locality: "Subhash Nagar",
			parentId: 325254,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3 kms",
			hasSurge: false,
			sla: {
				restaurantId: "677107",
				deliveryTime: 35,
				minDeliveryTime: 35,
				maxDeliveryTime: 35,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: true,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "430937",
			name: "Joshi Restaurant",
			uuid: "cd502152-0db3-4404-97ce-4f102881668f",
			city: "22",
			area: "Subhash Nagar",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "fl8tqkxshcqu4rfc0z9f",
			cuisines: ["Pizzas", "American", "Fast Food", "Indian", "Beverages"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 41,
			minDeliveryTime: 41,
			maxDeliveryTime: 41,
			slaString: "41 MINS",
			lastMileTravel: 3.5999999046325684,
			slugs: {
				restaurant: "joshi-restaurant-patel-nagar-patel-nagar",
				city: "dehradun",
			},
			cityState: "22",
			address: "C-20 RAM MANDIR TURNER ROAD OGGAL BHATTA CLEMENT TOWN DEHRADUN",
			locality: "Clement Town",
			parentId: 111523,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "430937",
				deliveryTime: 41,
				minDeliveryTime: 41,
				maxDeliveryTime: 41,
				lastMileTravel: 3.5999999046325684,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "628138",
			name: "Da Pizza King",
			uuid: "21bfb5d8-2740-4bb5-901c-a27f281e6fd2",
			city: "22",
			area: "Subhash Nagar",
			totalRatingsString: "Too Few Ratings",
			cloudinaryImageId: "wf1coyi5pmkxjijlzxyp",
			cuisines: ["Pizzas", "Burgers", "Pastas"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 41,
			minDeliveryTime: 41,
			maxDeliveryTime: 41,
			slaString: "41 MINS",
			lastMileTravel: 3.5999999046325684,
			slugs: {
				restaurant: "da-pizza-king-deh_patel-nagar-deh_patel-nagar",
				city: "dehradun",
			},
			cityState: "22",
			address:
				"C-20 Ram Mandir Turner Road Oggal Bhatta Clement Town Dehradun, Dehradun Nagar Nigam,  Dehradun, Uttarakhand",
			locality: "Turner Road",
			parentId: 67443,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off | Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "Use WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off up to ₹90 | Use code WELCOME50",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: "",
				title: "",
				amount: "",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "628138",
				deliveryTime: 41,
				minDeliveryTime: 41,
				maxDeliveryTime: 41,
				lastMileTravel: 3.5999999046325684,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "--",
			totalRatings: 0,
			new: false,
		},
		subtype: "basic",
	},
];

export const IMG_CDN_URL =
	"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
